addSbtPlugin("org.typelevel"      % "sbt-typelevel"                               % "0.7.7")
addSbtPlugin("org.typelevel"      % "sbt-typelevel-scalafix"                      % "0.7.7")
addSbtPlugin("org.typelevel"      % "sbt-typelevel-site"                          % "0.7.7")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                                 % "1.18.2")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"                            % "0.4.17")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject"               % "1.3.2")
addSbtPlugin("com.github.sbt"     % "sbt-javaagent"                               % "0.1.8")
addSbtPlugin("com.armanbilge"     % "sbt-scala-native-config-brew-github-actions" % "0.3.0")
