addSbtPlugin("org.typelevel"      % "sbt-typelevel"                               % "0.8.4")
addSbtPlugin("org.typelevel"      % "sbt-typelevel-scalafix"                      % "0.8.4")
addSbtPlugin("org.typelevel"      % "sbt-typelevel-site"                          % "0.8.4")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                                 % "1.20.2")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"                            % "0.5.9")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject"               % "1.3.2")
addSbtPlugin("com.github.sbt"     % "sbt-javaagent"                               % "0.2.0")
addSbtPlugin("com.armanbilge"     % "sbt-scala-native-config-brew-github-actions" % "0.4.0")
